#!/usr/bin/env python3
"""
copy last edited file to file with name such as `08-Aug-23.md`
"""

import glob
import os
from datetime import date
import shutil


def main():
    list_directory = glob.glob("./*")
    list_of_files = [f for f in list_directory if os.path.isfile(f)]
    last_edited_file = max(list_of_files, key=os.path.getmtime)

    today_date_string = date.today().strftime("%d-%b-%y")  # e.g. 10-Aug-23
    today_date_filename = f"{today_date_string}.md"

    if not os.path.exists(today_date_filename):
        print(f"copying {last_edited_file} to {today_date_filename}")
        shutil.copy(last_edited_file, today_date_filename)
        exit(0)  # good
    else:
        print(f"{today_date_filename} already exists!")
        exit(1)  # bad


if __name__ == "__main__":
    main()
