#!/usr/bin/env python3
def main(raw_branch_name):
    jira_board, jira_ticket_number, *raw_message = raw_branch_name.split('-')

    if jira_ticket_number.isdigit():
        message = " ".join(raw_message)
        git_message = f"{jira_board.upper()}-{jira_ticket_number} {message}"
    else:
        git_message = raw_branch_name.replace("-", " ")

    return git_message

assert main('JIRA-1234-testing-branch-name') == 'JIRA-1234 testing branch name' 
assert main('ad-hoc-no-ticket') == 'ad hoc no ticket' 

if __name__=="__main__":
    import subprocess
    result = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], stdout=subprocess.PIPE)
    raw_branch_name = result.stdout.decode('utf-8').strip()

    print(main(raw_branch_name))
