#!/bin/sh

brew install ripgrep

brew install autojump # command j

brew install bat # terminal syntax highlight

brew install fd

brew install jq

brew install fzf

brew install python3 # get latest python
python3 -m pip install -r requirements.txt

brew install vim  # get vim 9.0

# universal-ctags is better than `brew install ctags`
brew install universal-ctags

brew install git-delta

ln -s -v -F "$PWD"/.vimrc "$HOME"/.vimrc

ln -s -v -F "$PWD"/.gitconfig "$HOME"/.gitconfig
ln -s -v -F "$PWD"/.gitattributes "$HOME"/.config/git/.gitattributes
ln -s -v -F "$PWD"/.gitignore_global "$HOME"/.gitignore_global

ln -s -v -F "$PWD"/.zshrc "$HOME"/.zshrc


ln -s -v -F "$PWD"/.pdbrc "$HOME"/.pdbrc

ln -s -v -F "$PWD"/.fdignore "$HOME"/.fdignore

ln -s -v -F "$PWD"/.rgrc "$HOME"/.rgrc

ln -s -v -F "$PWD"/vim_python.py "$HOME"/.vim/python3/vim_python.py

ln -s -v -F "$PWD"/zsh.vim "$HOME"/.vim/after/syntax/zsh.vim
