#!/bin/sh

brew install ripgrep

brew install ctags

brew install autojump # command j

echo install vimrc
ln -s -F "$PWD"/.vimrc "$HOME"/.vimrc

echo install gitconfig
ln -s -F "$PWD"/.gitconfig "$HOME"/.gitconfig

echo install ctags configs
ln -s -F "$PWD"/.ctags "$HOME"/.ctags

echo install zshrc
ln -s -F "$PWD"/.zshrc "$HOME"/.zshrc

echo install git global ignores
ln -s -F "$PWD"/.gitignore_global "$HOME"/.gitignore_global

