#!/bin/sh
set -o errexit -o nounset -o xtrace

XDG_CONFIG_HOME="$HOME/.config"

echo soft linking dunst notification service config
mkdir -p "$XDG_CONFIG_HOME"/dunst
ln --symbolic --force "$PWD"/dunstrc "$XDG_CONFIG_HOME"/dunst/dunstrc

echo soft linking i3 config
mkdir -p "$XDG_CONFIG_HOME"/i3
ln --symbolic --force "$PWD"/i3-config "$XDG_CONFIG_HOME"/i3/config

echo soft linking i3status config
mkdir -p "$XDG_CONFIG_HOME"/i3status
ln --symbolic --force "$PWD"/i3status-config "$XDG_CONFIG_HOME"/i3status/config

echo install git global ignores
mkdir -p "$XDG_CONFIG_HOME"/git
ln --symbolic --force "$PWD"/.gitignore_global "$XDG_CONFIG_HOME"/git/ignore

echo install autorandr configs
ln --symbolic --force "$PWD"/autorandr "$XDG_CONFIG_HOME"/autorandr

echo install vim configs
ln --symbolic --force "$PWD"/.vimrc "$HOME"/.vimrc

echo install inputrc
ln --symbolic --force "$PWD"/.inputrc "$HOME"/.inputrc

echo install bash profile
ln --symbolic --force "$PWD"/.bash_profile "$HOME"/.bash_profile

echo install bashrc
ln --symbolic --force "$PWD"/.bashrc "$HOME"/.bashrc

echo install .profile, i3 exec replies on it
ln --symbolic --force "$PWD"/.profile "$HOME"/.profile

echo install ctags configs
ln --symbolic --force "$PWD"/.ctags "$HOME"/.ctags

# the dpi settings will be likely wrong in other laptops
# you can tweak it and git ignore locally this files
echo install X Window System files
ln --symbolic --force "$PWD"/.xinitrc "$HOME"/.xinitrc
ln --symbolic --force "$PWD"/.Xresources "$HOME"/.Xresources

echo install .gitconfig configs
ln --symbolic --force "$PWD"/.gitconfig "$HOME"/.gitconfig

echo install newsboat configs
ln --symbolic --force "$PWD"/config "$HOME"/.newsboat/

echo replace crontab with crontab in this repo
crontab "$PWD"/crontab

echo install vim jira syntax
mkdir -p "$HOME"/.vim/syntax/
ln --symbolic --force "$PWD"/.vim/syntax/jira.vim "$HOME"/.vim/syntax/

# https://askubuntu.com/questions/362914/how-to-prevent-the-power-button-to-shutdown-directly-the-system
echo avoid power button shutting down computer
logind_config=/etc/systemd/logind.conf
# https://stackoverflow.com/questions/4749330/how-to-test-if-string-exists-in-file-with-bash
if ! grep -Fxq 'HandlePowerKey=ignore' "$logind_config"
then
    echo 'HandlePowerKey=ignore' | sudo tee -a "$logind_config" > /dev/null
fi

echo enable DNS over TLS
resolved_config=/etc/systemd/resolved.conf
if ! grep -Fxq 'DNSOverTLS=yes' "$resolved_config"
then
    echo 'DNSOverTLS=yes' | sudo tee -a "$resolved_config" > /dev/null
fi
# set Blank Screen as never, never turn off screen
gsettings set org.gnome.desktop.session idle-delay 0
