#!/bin/sh
set -o errexit -o nounset -o xtrace

use_internal_sound_card_sink() {
   # turn off HDMI output
   pactl set-card-profile alsa_card.pci-0000_00_1f.3 off

   # set to use internal sound card sink
   # this is only needed when setting up bluetooth speaker, commented out for now
   # sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
   # pactl set-default-sink $sound_card_index
}

use_internal_sound_card_sink

# set to use earphone
sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
pactl set-card-profile "$sound_card_index" output:codec-output+input:codec-input

# unmute audio
pactl set-sink-mute @DEFAULT_SINK@ false

# set volume to 10 percent perfect for listening to music
pactl set-sink-volume @DEFAULT_SINK@ 10%

notify-send 'Using Music Mode'
