#!/usr/bin/env python3
"""
Always exit with 0 success, otherwise i3status will stop.
"""
import subprocess
import signal
import requests
import requests

def handler(signum, frame):
    res = input("Ctrl-c was pressed. Exiting!")
    exit(1)

signal.signal(signal.SIGINT, handler)

proc = subprocess.Popen(["i3status"], universal_newlines=True, stdout=subprocess.PIPE)

# counter to avoid network request all the time
counter = 0
for line in proc.stdout:
    formatted_line = line.strip()

    # when a field is empty, i3status output 'BATTERY 99% |  | 10/26 09:19'
    # remove the unnecessary "|  |"
    if "VPN" not in line:
        formatted_line = formatted_line.replace(" |  | ", " | ")

    if counter == 0:
        try:
            response = requests.get("https://wttr.in/?format=%C%t")
            response.raise_for_status()
        except requests.exceptions.HTTPError as err:
            pass

    # change temperature +19 to 19 and tr to change to uppercase
    weather = response.text.strip().upper().replace("+", " ")

    print(weather, "|", formatted_line)

    counter += 1
    if counter > 100:
        counter = 0







exit()
