#!/bin/sh
set -o errexit -o nounset -o xtrace

current_monitor=$(xrandr | grep "\bconnected primary" | cut -d " " -f 1)
available_external_monitor=$(xrandr | grep '\bconnected' | grep -v eDP | cut -d " " -f 1)
internal_monitor=$(xrandr | grep '\bconnected' | grep eDP | cut -d " " -f 1)

# if there is not available_external_monitor, always use internal_monitor
[ -z "$available_external_monitor" ] && \
    xrandr --output "$internal_monitor" --auto --primary && \
    exit 0


# DP2 is the external monitor
# eDP1 is the internal monitor
case $current_monitor in
$available_external_monitor) # external monitor
    # use internal monitor
    xrandr --output "$current_monitor" --off --output "$internal_monitor" --auto --primary
    ;;
"$internal_monitor") # internal monitor
    # use external monitor
    xrandr --output "$available_external_monitor" --auto --primary --output "$internal_monitor" --off
    ;;
esac
