#!/bin/sh
set -o errexit -o nounset -o xtrace

use_internal_sound_card_sink() {
   # turn off HDMI output
   pactl set-card-profile alsa_card.pci-0000_00_1f.3 off

   # set to use internal sound card sink
   # this is only needed when setting up bluetooth speaker, commented out for now
   # sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
   # pactl set-default-sink $sound_card_index
}

earphone() {
   use_internal_sound_card_sink

   # set to use earphone
   sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
   pactl set-card-profile $sound_card_index output:codec-output+input:codec-input
}

speaker() {
   use_internal_sound_card_sink

   # set to use speaker
   sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
   pactl set-card-profile $sound_card_index output:builtin-speaker+input:builtin-mic
}

active_output=$(pactl list | grep Active.Profile | grep -v off | grep -v hdmi | cut -d " " -f 3)

# TODO handle bluetooth speaker
case $active_output in
output:builtin-speaker+input:builtin-mic)
    earphone
    ;;
output:codec-output+input:codec-input)
    speaker
    ;;
esac
