#!/bin/sh
set -o errexit -o nounset -o xtrace

use_internal_sound_card_sink() {
   # turn off HDMI output
   pactl set-card-profile alsa_card.pci-0000_00_1f.3 off

   # set to use internal sound card sink
   # this is only needed when setting up bluetooth speaker, commented out for now
   # sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
   # pactl set-default-sink $sound_card_index
}

use_internal_sound_card_sink

# set to use earphone
sound_card_index=$(pactl list cards | grep -B10 "Apple T2 Audio" | head -n1 | cut -d "#" -f2)
pactl set-card-profile "$sound_card_index" output:builtin-speaker+input:builtin-mic

# unmute audio
pactl set-sink-mute @DEFAULT_SINK@ false

# video_mode.txt is private, the first line will be volume (60%), the second line will be url (https://...)
video_mode_volume=$(sed -n '1p' "$HOME/Documents/dotfiles/video_mode.txt")
video_mode_url=$(sed -n '2p' "$HOME/Documents/dotfiles/video_mode.txt")

pactl set-sink-volume @DEFAULT_SINK@ "$video_mode_volume"
i3-msg "workspace 1:Video; exec google-chrome --new-window $video_mode_url"

notify-send 'Using Video Mode'
